// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// RustQuant: A Rust library for quantitative finance tools.
// Copyright (C) 2023 https://github.com/avhz
// Dual licensed under Apache 2.0 and MIT.
// See:
//      - LICENSE-APACHE.md
//      - LICENSE-MIT.md
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/// ISO 4217 codes enum.
///
/// Format:
///     - First two letters are the ISO 3166-1 alpha-2 country code. e.g. US = United States
///     - Third letter is the first letter of the currency name. e.g. USD = United States Dollar
///     - The number is the ISO numeric code. e.g. 840 = USD
#[derive(Debug, Clone, Copy)]
#[allow(non_camel_case_types)]
pub struct ISO_4217 {
    /// The ISO 4217 alphabetic code.
    pub alphabetic: &'static str,

    /// The ISO 4217 numeric code.
    pub numeric: &'static str,
}

// /// Macro to generate all ISO 4217 country codes.
// macro_rules! iso_4217 {
//     ($($name:ident: $alphabetic:literal, $numeric:literal,)*) => {
//         $(
//             /// $name
//             pub const $name: ISO_4217 = ISO_4217 {
//                 alphabetic: $alphabetic,
//                 numeric: $numeric,
//             };
//         )*
//     };
// }

// iso_4217! {
//     AED: "AED", "784",
//     AFN: "AFN", "971",
//     ALL: "ALL", "008",
//     AMD: "AMD", "051",
//     ANG: "ANG", "532",
//     AOA: "AOA", "973",
//     ARS: "ARS", "032",
//     AUD: "AUD", "036",
//     AWG: "AWG", "533",
//     AZN: "AZN", "944",
//     BAM: "BAM", "977",
//     BBD: "BBD", "052",
//     BDT: "BDT", "050",
//     BGN: "BGN", "975",
//     BHD: "BHD", "048",
//     BIF: "BIF", "108",
//     BMD: "BMD", "060",
//     BND: "BND", "096",
//     BOB: "BOB", "068",
//     BOV: "BOV", "984",
//     BRL: "BRL", "986",
//     BSD: "BSD", "044",
//     BTN: "BTN", "064",
//     BWP: "BWP", "072",
//     BYN: "BYN", "933",
//     BZD: "BZD", "084",
//     CAD: "CAD", "124",
//     CDF: "CDF", "976",
//     CHE: "CHE", "947",
//     CHF: "CHF", "756",
//     CHW: "CHW", "948",
//     CLF: "CLF", "990",
//     CLP: "CLP", "152",
//     CNY: "CNY", "156",
//     COP: "COP", "170",
//     COU: "COU", "970",
//     CRC: "CRC", "188",
//     CUC: "CUC", "931",
//     CUP: "CUP", "192",
//     CVE: "CVE", "132",
//     CZK: "CZK", "203",
//     DJF: "DJF", "262",
//     DKK: "DKK", "208",
//     DOP: "DOP", "214",
//     DZD: "DZD", "012",
//     EGP: "EGP", "818",
//     ERN: "ERN", "232",
//     ETB: "ETB", "230",
//     EUR: "EUR", "978",
//     FJD: "FJD", "242",
//     FKP: "FKP", "238",
//     GBP: "GBP", "826",
//     GEL: "GEL", "981",
//     GHS: "GHS", "936",
//     GIP: "GIP", "292",
//     GMD: "GMD", "270",
//     GNF: "GNF", "324",
//     GTQ: "GTQ", "320",
//     GYD: "GYD", "328",
//     HKD: "HKD", "344",
//     HNL: "HNL", "340",
//     HRK: "HRK", "191",
//     HTG: "HTG", "332",
//     HUF: "HUF", "348",
//     IDR: "IDR", "360",
//     ILS: "ILS", "376",
//     INR: "INR", "356",
//     IQD: "IQD", "368",
//     IRR: "IRR", "364",
//     ISK: "ISK", "352",
//     JMD: "JMD", "388",
//     JOD: "JOD", "400",
//     JPY: "JPY", "392",
//     KES: "KES", "404",
//     KGS: "KGS", "417",
//     KHR: "KHR", "116",
//     KMF: "KMF", "174",
//     KPW: "KPW", "408",
//     KRW: "KRW", "410",
//     KWD: "KWD", "414",
//     KYD: "KYD", "136",
//     KZT: "KZT", "398",
//     LAK: "LAK", "418",
//     LBP: "LBP", "422",
//     LKR: "LKR", "144",
//     LRD: "LRD", "430",
//     LSL: "LSL", "426",
//     LYD: "LYD", "434",
//     MAD: "MAD", "504",
//     MDL: "MDL", "498",
//     MGA: "MGA", "969",
//     MKD: "MKD", "807",
//     MMK: "MMK", "104",
//     MNT: "MNT", "496",
//     MOP: "MOP", "446",
//     MRU: "MRU", "929",
//     MUR: "MUR", "480",
//     MVR: "MVR", "462",
//     MWK: "MWK", "454",
//     MXN: "MXN", "484",
//     MXV: "MXV", "979",
//     MYR: "MYR", "458",
//     MZN: "MZN", "943",
//     NAD: "NAD", "516",
//     NGN: "NGN", "566",
//     NIO: "NIO", "558",
//     NOK: "NOK", "578",
//     NPR: "NPR", "524",
//     NZD: "NZD", "554",
//     OMR: "OMR", "512",
//     PAB: "PAB", "590",
//     PEN: "PEN", "604",
//     PGK: "PGK", "598",
//     PHP: "PHP", "608",
//     PKR: "PKR", "586",
//     PLN: "PLN", "985",
//     PYG: "PYG", "600",
//     QAR: "QAR", "634",
//     RON: "RON", "946",
//     RSD: "RSD", "941",
//     RUB: "RUB", "643",
//     RWF: "RWF", "646",
//     SAR: "SAR", "682",
//     SBD: "SBD", "090",
//     SCR: "SCR", "690",
//     SDG: "SDG", "938",
//     SEK: "SEK", "752",
//     SGD: "SGD", "702",
//     SHP: "SHP", "654",
//     SLL: "SLL", "694",
//     SOS: "SOS", "706",
//     SRD: "SRD", "968",
//     SSP: "SSP", "728",
//     STN: "STN", "930",
//     SVC: "SVC", "222",
//     SYP: "SYP", "760",
//     SZL: "SZL", "748",
//     THB: "THB", "764",
//     TJS: "TJS", "972",
//     TMT: "TMT", "934",
//     TND: "TND", "788",
//     TOP: "TOP", "776",
//     TRY: "TRY", "949",
//     TTD: "TTD", "780",
//     TWD: "TWD", "901",
//     TZS: "TZS", "834",
//     UAH: "UAH", "980",
//     UGX: "UGX", "800",
//     USD: "USD", "840",
//     USN: "USN", "997",
//     UYI: "UYI", "940",
// }
